import type { Card, Deck } from '../types'

export interface SeedDeck {
  deck: Deck
  cards: Card[]
}

/**
 * The starter deck every new user receives on first run. Generated by
 * `bun scripts/make-seed.ts <backup.json> "<Deck Name>"` from an exported
 * backup (images inlined as data URLs; IDs + timestamps frozen so a later
 * deletion always wins over a re-seed on another device). `null` until
 * generated — the seeding step no-ops while it's null.
 */
const seed: SeedDeck | null = null

export default seed
