#!/usr/bin/env bun
/**
 * Turn one deck from an exported PawCards backup into the bundled starter deck
 * (src/lib/seed/exampleDeck.ts) that every new user is seeded with on first run.
 *
 *   1. In the app, build the deck and ✨ its images.
 *   2. Settings → Export backup WHILE ONLINE (that inlines images to data URLs).
 *   3. bun scripts/make-seed.ts ~/Downloads/pawcards-backup-YYYY-MM-DD.json "Example Deck"
 *
 * IDs are kept (so a multi-device user dedupes) and timestamps are frozen old
 * (so a later deletion always beats a re-seed on another device); SRS is reset
 * so everyone starts the deck fresh.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const [backupPath, deckName] = process.argv.slice(2)
if (!backupPath || !deckName) {
  console.error('usage: bun scripts/make-seed.ts <backup.json> "<Deck Name>"')
  process.exit(1)
}

// fixed & safely in the past — the seed must always lose to any real user edit/delete in sync merge
const SEED_TS = 1_700_000_000_000

interface AnyCard {
  id: string
  deckId: string
  polished?: { front?: string }
  [k: string]: unknown
}
interface AnyDeck {
  id: string
  name: string
  [k: string]: unknown
}

let backup: { decks?: AnyDeck[]; cards?: AnyCard[] }
try {
  backup = JSON.parse(readFileSync(backupPath, 'utf8'))
} catch (e) {
  console.error(`could not read/parse ${backupPath}: ${(e as Error).message}`)
  process.exit(1)
}

const deck = (backup.decks ?? []).find((d) => d.name === deckName)
if (!deck) {
  console.error(`no deck named "${deckName}" in ${backupPath}. Decks present: ${(backup.decks ?? []).map((d) => `"${d.name}"`).join(', ') || '(none)'}`)
  process.exit(1)
}
const cards = (backup.cards ?? []).filter((c) => c.deckId === deck.id)
if (!cards.length) {
  console.error(`deck "${deckName}" has no cards`)
  process.exit(1)
}

const unresolved = cards.filter((c) => typeof c.polished?.front === 'string' && c.polished.front.startsWith('img:')).length
if (unresolved) {
  console.error(
    `✗ ${unresolved} card image(s) are still "img:" refs, not data URLs.\n` +
      '  Re-export the backup WHILE ONLINE so the images are inlined, then re-run.',
  )
  process.exit(1)
}

const freeze = <T extends object>(o: T): T => ({ ...o, created: SEED_TS, updated: SEED_TS })
const seed = {
  deck: freeze({ ...deck, sharedBy: undefined }),
  cards: cards.map((c) => freeze({ ...c, srs: null })),
}
// JSON round-trip drops the undefined sharedBy
const clean = JSON.parse(JSON.stringify(seed))

const outDir = join(dirname(fileURLToPath(import.meta.url)), '../src/lib/seed')
mkdirSync(outDir, { recursive: true })
const out = join(outDir, 'exampleDeck.ts')
writeFileSync(
  out,
  `import type { Card, Deck } from '../types'\n\n` +
    `export interface SeedDeck {\n  deck: Deck\n  cards: Card[]\n}\n\n` +
    `// Generated by scripts/make-seed.ts from "${deckName}" — do not edit by hand.\n` +
    `const seed: SeedDeck = ${JSON.stringify(clean)}\n\nexport default seed\n`,
)
const kb = (readFileSync(out).length / 1024).toFixed(0)
console.log(`✓ wrote ${out}`)
console.log(`  deck "${deckName}" · ${cards.length} cards · ${kb} KB (bundled as a lazy chunk)`)
console.log('  bump APP_VERSION and ship — new users get it; existing users already have the flag set.')
